# basic

avatar: images/avatar.png
banner_large: images/banner-large.jpg

disqus_shortname: dao-challenge

# social
social:
  github: https://github.com/sjors/dao-challenge
  twitter: https://twitter.com/provoost

nav:
  home: .
  # archive: archives
  # about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
